import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
// import Sidebar from "./components/Sidebar";
// import Header from "./components/Header";
import "react-toastify/dist/ReactToastify.css";
// import { usePathname } from "next/navigation";
import { ToastContainer } from "react-toastify";
import RootlayoutWrapper from "./components/RootlayoutWrapper";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();

  return (
    <html lang="en">
      <body className={` antialiased flex  h-full bg-[#FBF4EB] `}>
        <ToastContainer />
        <RootlayoutWrapper />
        <div className="h-full w-full">{children}</div>
      </body>
    </html>
  );
}
